name: mensaeria_alv
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  animated_segmented_tab_control: ^1.2.0
  build_context_provider: ^1.1.0
  dio: ^5.3.3
  dropdown_button2: ^2.3.9
  easy_date_timeline: ^0.1.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_emoji_feedback: ^0.1.2
  flutter_riverpod: ^2.4.3
  flutter_staggered_grid_view: ^0.7.0
  fluttertoast: ^8.2.2
  formz: ^0.6.1
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  google_nav_bar: ^5.0.6
  intl: ^0.18.1
  lottie: ^2.7.0
  shared_preferences: ^2.2.2
  socket_io_client: ^2.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/loaders/
    - assets/images/
    - google_fonts/montserrat_alternates/
